kind: Deployment
apiVersion: apps/v1
metadata:
  name: zerotrustapi
  labels:
    app: zerotrustapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerotrustapi
  template:
    metadata:
      labels:
        app: zerotrustapi
    spec:
      serviceAccountName: zerotrustapi
      containers:
      - name: zerotrustapi
        image: zerotrustapi:1.0.0
        env:
          - name: NODE_ENV
            value: 'production'
          - name: PORT
            value: '8000'
          - name: JWKS_URI
            value: 'http://curity-idsvr-runtime-svc.authorizationserver:8443/oauth/v2/oauth-anonymous/jwks'
          - name: REQUIRED_JWT_ALGORITHM
            value: 'ES256'
          - name: 'REQUIRED_ISSUER'
            value: 'http://login.examplecluster.com/oauth/v2/oauth-anonymous'
          - name: 'REQUIRED_AUDIENCE'
            value: 'api.example.com'
          - name: 'REQUIRED_SCOPE'
            value: 'retail/orders'
          - name: 'AUTHORIZATION_STRATEGY'
            value: 'policy' # Enable authorization with OPA
          - name: 'POLICY_ENDPOINT'
            value: 'http://127.0.0.1:8181/v1/data/orders/allow' # URL to query policy on OPA
      initContainers:
      - name: policyengine
        image: openpolicyagent/opa:latest
        restartPolicy: Always
        args:
          - "run"
          - "--ignore=.*" # Ignore kubernetes specific files
          - "--server"
          - "--addr"
          - "127.0.0.1:8181" # Listen on local interface
          - "--set"
          - "decision_logs.console=true" # Enable decision logs
          - "--set" 
          - "services.policyRetrievalPoint.url=http://policy-retrieval-point-svc" # Base-URL of server hosting the policy bundle
          - "--set"
          - "bundles.policyRetrievalPoint.resource=bundle.tar.gz" # Path of policy bundle on server
          - "--set"
          - "bundles.policyRetrievalPoint.persist=false" # Keep policy in memory
          - "--v1-compatible"
