kind: Deployment
apiVersion: apps/v1
metadata:
  name: zerotrustapi
  labels:
    app: zerotrustapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerotrustapi
  template:
    metadata:
      labels:
        app: zerotrustapi
    spec:
      serviceAccountName: zerotrustapi
      containers:
      - name: zerotrustapi
        image: zerotrustapi:1.0.0
        env:
          - name: NODE_ENV
            value: 'production'
          - name: PORT
            value: '8000'
          - name: JWKS_URI
            value: 'http://curity-idsvr-runtime-svc.authorizationserver:8443/oauth/v2/oauth-anonymous/jwks'
          - name: REQUIRED_JWT_ALGORITHM
            value: 'ES256'
          - name: 'REQUIRED_ISSUER'
            value: 'https://login.democluster.example/oauth/v2/oauth-anonymous'
          - name: 'REQUIRED_AUDIENCE'
            value: 'api.example.com'
          - name: 'REQUIRED_SCOPE'
            value: 'retail/orders'
          - name: 'AUTHORIZATION_STRATEGY'
            value: 'code'

