replicaCount: 2

image:
  #
  # DELETEME: Revert to the official latest image before merging
  #
  repository: curity/idsvr-unstable
  tag: 10.0.0-76088f8571

curity:
  adminUiHttp: true
  admin:
    #
    # DELETEME: Prerelease containers build as root - remove the security context settings before merging
    #
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    podLabels:
      sidecar.istio.io/inject: 'true'
      spire-managed-identity: 'true'
    podAnnotations:
      inject.istio.io/templates: 'sidecar,spire'
    service:
      annotations:
        ingress.kubernetes.io/service-upstream: 'true'
    serviceAccount:
      name: curity-idsvr-admin
    logging:
      level: INFO

  runtime:
    #
    # DELETEME: Prerelease containers build as root - remove the security context settings before merging
    #
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    podLabels:
      sidecar.istio.io/inject: 'true'
      spire-managed-identity: 'true'
    podAnnotations:
      inject.istio.io/templates: 'sidecar,spire'
    service:
      annotations:
        ingress.kubernetes.io/service-upstream: 'true'
    serviceAccount:
      name: curity-idsvr-runtime
    logging:
      level: INFO
    
  config:
    uiEnabled: true
    skipInstall: true
    configuration:
      - configMapRef:
          name: idsvr-configbackup
          items:
          - key: config-backup
            path: config-backup.xml

    environmentVariableConfigMaps:
    - idsvr-parameters
    environmentVariableSecrets:
    - idsvr-protected-parameters

networkpolicy:
  enabled: false
