#
# Customized values for the Kong gateway from the base file here
# https://github.com/Kong/charts/blob/main/charts/kong/values.yaml
#

#
# A custom Docker image containing the phantom token plugin's dependencies
#
image:
  repository: custom-kong
  tag: 1.0.0

ingressController:
  env:
    feature_gates: RewriteURIs=true

#
# Plugins are deployed as configmaps, then applied to one or more routes
# Files are deployed to the Kong 'proxy' container at these locations:
# - /opt/kong/plugins/phantom-token
# - /opt/kong/plugins/oauth-proxy
#
plugins:
  configMaps:
  - pluginName: oauth-proxy
    name: curity-oauth-proxy
  - pluginName: phantom-token
    name: curity-phantom-token

#
# Override the default SSL certificate that Kong generates
#
secretVolumes:
- external-tls

#
# Also provide an NGINX cache for the caching of introspection results
#
env:
  nginx_http_lua_shared_dict: 'phantom-token 10m'
