############################################################################
# Parameters for the gateway Helm chart
# - https://artifacthub.io/packages/helm/istio-official/istiod?modal=values
#
# - Set the label so that the gateway is registered with SPIRE
# - Set a template so that the gateway mounts the SPIFFE CSi driver
############################################################################
defaults:
  labels:
    spire-managed-identity: 'true'
    
  podAnnotations:
    inject.istio.io/templates: 'gateway,spire-gw'
