apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-retrieval-point
  labels:
    app.kubernetes.io/name: policy-retrieval-point
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: policy-retrieval-point
  template:
    metadata:
      labels:
        app.kubernetes.io/name: policy-retrieval-point
      name: orders-policy-bundle
    spec:
      containers:
      - name: apache2-httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - readOnly: true
          mountPath: /usr/local/apache2/htdocs/
          name: orders-policy-volume
      volumes:
      - name: orders-policy-volume
        configMap:
          name: orders-policy-bundle
