kind: Service
apiVersion: v1
metadata:
  name: policy-retrieval-point-svc
spec:
  selector:
    app.kubernetes.io/name: policy-retrieval-point
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80